### ISSUE TITLE
JL_BLEKit 能否添加 ix86 模拟器架构

### ISSUE THREAD

**Issue by MrXCQ** [Jieli-Tech/iOS-JL_OTA#13]
JL_BLEKit 能否添加 ix86 模拟器架构

**Comment by MrXCQ** [comment]
蓝牙BLE不影响，主要是能够支持模拟器运行，方便使用者调试。

**Comment by MrXCQ** [comment]
很不错，谢谢！

**Comment by MrXCQ** [comment]
![image](https://user-images.githubusercontent.com/15794342/197663018-6a5216fb-64f2-4f55-82d8-34a2ea403b26.png)
这个库在真机上会崩溃呢

**Comment by EzioChen** [comment]
new commit fix this bug
