### ISSUE TITLE
OTA升级失败，卡在校验文件完成100%

### ISSUE THREAD

**Issue by MasterYou** [Jieli-Tech/iOS-JL_OTA#15]
你好，做ota升级的时候，同一个蓝牙，同一个升级文件，网络下载的安卓app能够实现升级成功，appstore下载和demo运行的app，会卡在校验文件完成100%，升级过程中didUpdateNotificationStateForCharacteristic会出现AE02的isNotifying的值为false的情况，然后就提示升级超时，这个是不是得由蓝牙工程师解决？但是安卓的能实现正常升级。
是否有其他的联系方式方便提供一下？

**Comment by EzioChen** [comment]
请提供对应的相关日志

**Comment by EzioChen** [comment]
> 你好，做ota升级的时候，同一个蓝牙，同一个升级文件，网络下载的安卓app能够实现升级成功，appstore下载和demo运行的app，会卡在校验文件完成100%，升级过程中didUpdateNotificationStateForCharacteristic会出现AE02的isNotifying的值为false的情况，然后就提示升级超时，这个是不是得由蓝牙工程师解决？但是安卓的能实现正常升级。 是否有其他的联系方式方便提供一下？

请提供对应的相关日志
