### ISSUE TITLE
使用JL_BLEKIT如何去发送自定义的指令

### ISSUE THREAD

**Issue by huoda1237** [Jieli-Tech/iOS-JL_OTA#17]
你好，我现在需要给设备发送特定的指令以获取制定的信息，请问该使用什么方法发送呢？是使用JL_EntityM这个类里面的
-(void)xmCommandCode:(uint8_t)cmdCode
             needRep:(BOOL)needResponse
                data:(NSData *)sendData;
这个方法吗？如果是的话那接收的数据在哪里呢？

**Comment by EzioChen** [comment]
开发时可参考开发文档
https://doc.zh-jieli.com/Apps/iOS/health/zh-cn/master/Development/Content/function_desc.html#id128
