### ISSUE TITLE
麻烦问一下，JL_OTAResult中的回连及重启触发机制是什么？哪些情况会出现此类状态，如何验证？

### ISSUE THREAD

**Issue by Doris1994** [Jieli-Tech/iOS-JL_OTA#18]
JL_OTAResultReconnect           = 0x09, //OTA需重连设备(uuid方式)
 JL_OTAResultReboot              = 0x0a, //OTA需设备重启
JL_OTAResultReconnectWithMacAddr = 0xfc, //OTA需重连设备(mac方式)

**Comment by EzioChen** [comment]
回连是设备单备份升级过程中，完成了一阶段的传输后，有一个断开重连的流程，这时候会触发 **JL_OTAResultReconnect = 0x09, //OTA需重连设备(uuid方式)** 或 **JL_OTAResultReconnectWithMacAddr = 0xfc, //OTA需重连设备(mac方式)** 具体会根据设备的特性来选择其中一条回连，**JL_OTAResultReboot = 0x0a, //OTA需设备重启** 只会在 OTA 升级传输完成后，设备端通知 app 端，设备需要重启，app 端即将断开
