### ISSUE TITLE
APP断开重连ANCS设备，回连失败怎么处理？

### ISSUE THREAD

**Issue by iCodeHP** [Jieli-Tech/iOS-JL_OTA#7]
1、ANCS设备连接APP就算APP断开BLE，但设备的BLE依然会与iPhone保持后台连接。那么此时在APP中搜索设备BLE是搜不到，需要用通过UUID回连设备，可以暂存上次连接时的UUID。

2、就算连接上了BLE握手配对失败如何处理？那么请将固件Log发送给我们的杰理OTA固件同事。

**Comment by EzioChen** [comment]
ANCS 参考 https://www.jianshu.com/p/43836fd36595
